### ISSUE TITLE
edit associations

### ISSUE THREAD

**Issue by lhahne** [CSC-IT-Center-for-Science/iow-ui#105]

**Comment by lhahne** [comment]
basic editing done. Adding missing values does not work (fields missing in context)

**Comment by amiika** [comment]
Context fixed? Fix value range (values="attributeValues") to Class list from Class API.

**Comment by amiika** [comment]
Add association range from "Select class" dialog. #108

**Comment by lhahne** [comment]
Edit works. I'll create new ticker for adding range.
