### ISSUE TITLE
Changing language should be obvious not under "Suomeksi"

### ISSUE THREAD

**Issue by amiika** [CSC-IT-Center-for-Science/iow-ui#201]
Separate buttons "Suomeksi" and "In english" to the main menu?

**Comment by amiika** [comment]
Also it would be nice to have lang uri parameter, for example: iow.csc.fi?lang=en

**Comment by mortterna** [comment]
What about user preference instead of url parameter? Users don't usually switch languages and when linking a for example class from model the audience might not want the authors language preference.

**Comment by amiika** [comment]
You might want to share a resource with a certain language and parameter is needed for that. The parameter should be the same as the main language which can be changed.
