### ISSUE TITLE
Should be possible to select shapes or classes in "value class / Kohde"

### ISSUE THREAD

**Issue by amiika** [CSC-IT-Center-for-Science/iow-ui#316]
Should be possible to select Shapes or Classes to association "range" (value class / Kohde).

valueClass was also changed to valueShape, check entities.

**Comment by amiika** [comment]
This is currently possible in production but is buggy after the shape is added.

**Comment by mortterna** [comment]
Define buggy? More information needed to be fixed. Does it reproduce in master?
