### ISSUE TITLE
When predicate is fetched using uuid, defined by is missing type

### ISSUE THREAD

**Issue by mortterna** [CSC-IT-Center-for-Science/iow-ui#345]
"isDefinedBy" : "http://iow.csc.fi/ns/edu"

**Comment by amiika** [comment]
All data should be stored in uuid graphs ... this can be "fixed" only by adding the model type in UI or adding model type in predicateCreator ... and same applies to other creators.

**Comment by amiika** [comment]
Joined model label and type from core service to Predicate&Class creator
