### ISSUE TITLE
Add sh:stem to class property associations

### ISSUE THREAD

**Issue by amiika** [CSC-IT-Center-for-Science/iow-ui#419]
Add input for sh:stem for class associations. 
Stem is used to validate that uri starts with given scheme.

Label: URL rakenne / URL stem

Add suggestion box for values:

http://
https://
data:
mailto:
tel:
urn:

However, not limited to these values. Can be any partial or full uri. eg: http://example.org/persons/whatever/

**Comment by mortterna** [comment]
Show stem in visualization
