### ISSUE TITLE
Visualization saved locations

### ISSUE THREAD

**Issue by mortterna** [CSC-IT-Center-for-Science/iow-ui#465]
nyt tuolla on sellainen kuin /modelPositions

PUT / GET

mutta saa myös exportModelin kautta ulos
eli käytännössä joinaa mallin exporttiin jonka tunkee tuolta modelPositions läpi
export API pitäs toimia myös vähän nopeammin nyt kun se tehdään valmiiksi aina muutosten 
jälkeen

ja datan osalta mennään sit tällä:
 {
  "@context": {
    "vertexXY": {
      "@id": "http://iow.csc.fi/ns/iow#vertexXY",
      "@container": "@list"
    },
    "pointXY": {
      "@id": "http://iow.csc.fi/ns/iow#pointXY"
    },
    "predicate": {
      "@id": "http://www.w3.org/ns/shacl#predicate"
    },
    "valueClass": {
      "@id": "http://www.w3.org/ns/shacl#valueClass"
    },
    "property": {
      "@id": "http://www.w3.org/ns/shacl#property"
    },
    "iow": "http://iow.csc.fi/ns/iow#",
    "jhs": "http://iow.csc.fi/ns/jhs#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "sh": "http://www.w3.org/ns/shacl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "jhs:Henkilo",
      "@type": "rdfs:Class",
      "pointXY": "200,400",
      "property": {
        "@id": "urn:uuid:8e440457-dd2d-4ac9-bb6c-65004e77a78a",
        "vertexXY": [
          "123,435",
          "234,327"
        ]
      }
    },
    {
      "@id": "jhs:Yhteystiedot",
      "@type": "rdfs:Class",
      "pointXY": "700,800"
    }
  ]
}

eli /modelPosition PUT kautta ei tarvitse välttämättä työntää kuin tuo mikä on jhs:Yhteystiedot luokalla ... mutta jos on vertexejä niin sit tuo ylempi ja huom @container @list.
mutta nyt jotain sapuskata

samantien voisi avata issuen myös "Layout" napista joka tekee layoutin uudestaan
elikkäs kaksi uutta nappia layout ja save ... joista save pitäisi näkyä vain kirjautuneena

**Comment by amiika** [comment]
mutta nyt jotain sapuskata :smile:

**Comment by mortterna** [comment]
figure out change of class id
