### ISSUE TITLE
Add language filter to search dialogs

### ISSUE THREAD

**Issue by amiika** [CSC-IT-Center-for-Science/iow-ui#474]
Implement filter to:

Code search
Class search
Predicate search
Concept search (This might require API work first)
Generic search in front page

Filter values: All languages (Languages defined in model) / Selected language

**Comment by mortterna** [comment]
Language is required parameter in search api that front page uses just like with concept search.

**Comment by amiika** [comment]
Added lang as optional to /search api. /conceptSearch needs more work.
