### ISSUE TITLE
Figure out how to use cleaner URLs for frontend

### ISSUE THREAD

**Issue by mortterna** [CSC-IT-Center-for-Science/iow-ui#485]

**Comment by amiika** [comment]
Some apache configuration could help. For example: https://ngmilk.rocks/2015/03/09/angularjs-html5-mode-or-pretty-urls-on-apache-using-htaccess/

But it should work with the current implementation of resolving uris under /ns/. Current apache configuration for that is one liner something like:

Redirect 303 /ns/ /api/rest/resolve
