### ISSUE TITLE
Dont send empty strings to API

### ISSUE THREAD

**Issue by amiika** [CSC-IT-Center-for-Science/iow-ui#558]
Change empty strings "" to null

**Comment by amiika** [comment]
},
      {
        "@id": "urn:uuid:cf214fe6-c339-4434-9c02-ce1d12593e7d",
        "created": "2016-03-15T11:32:28.523+02:00",
        "comment": {
          "fi": ""
        },
        "label": {
          "fi": "ok"
        },
        "versionInfo": "Unstable",
        "datatype": "xsd:string",
        "index": 1,
        "minCount": 1,
        "predicate": "http://iow.csc.fi/ap/oiliu#organisaatio",
        "identifier": "",
        "pattern": "",
        "editorialNote": {},
        "isResourceIdentifier": false,
        "inValues": [
          " 1",
          " 10",
          " 101"
        ],

**Comment by mortterna** [comment]
Binding empty strings is angular default behavior. New directive that binds empty as null needs to be added to every input or hook to entity serialization logic.
