### ISSUE TITLE
Opening association causes >10 calls to same codeValues API

### ISSUE THREAD

**Issue by amiika** [CSC-IT-Center-for-Science/iow-ui#559]
Test: http://iowdev.csc.fi/model/oiliu/OiliSanoma/cf214fe6-c339-4434-9c02-ce1d12593e7d

http://recordit.co/aNWn1bs6r7

**Comment by mortterna** [comment]
Not really a bug. Problem is caused by multiple inputs (Example, Default Value, Fixed Value) eagerly doing validation before code values result is cached. Caching can be improved by caching promises instead of actual result values.
