### ISSUE TITLE
edit id

### ISSUE THREAD

**Issue by lhahne** [CSC-IT-Center-for-Science/iow-ui#88]
* classes and attributes -> display id's
* edit id (not prefix)

**Comment by amiika** [comment]
... new id and old id are both needed in the Class/Property API when changing id:s. Adding newID parameter to POST API:s. #93

**Comment by amiika** [comment]
CLASS and PROPERTY apis now support changing id (removing old resource and updating references).

Now if you want to change class id, for example from "@id": "doo:KoulutuksenToteutus" to "@id":"doo:KoulutuksenToteutuma"

You have to post to Class-api with JSON-LD with the changed data ... "@id":"doo:KoulutuksenToteutuma" ... and POST using old and the new id:

id=doo:KoulutuksenToteutus
newid=doo:KoulutuksenToteutuma.

**Comment by lhahne** [comment]
editing implemented, saving not

**Comment by lhahne** [comment]
Should work.

@amiika please verify that no extra stuff is left behind in fuseki so that we can close this.

**Comment by amiika** [comment]
Seems to be working just fine
