### ISSUE TITLE
display datatype or valuclass for predicate based on property

### ISSUE THREAD

**Issue by lhahne** [CSC-IT-Center-for-Science/iow-ui#92]

**Comment by lhahne** [comment]
Miika
@Lauri, Pitäisi olla arvoalue (datatype/valueClass) ja Tyyppi (@type)
muuten ei voi olla varma onko tuo assosiaatioa vai attribuutti
Lauri
ok
Miika
voi olla myös vaihtoehtoisesti "Property type" ja "Ominaisuuden tyyppi" niin on ehkä selkeämpi kaikille
ja siis molemmat, Range=Arvoalue ja Property type (type)=Ominaisuuden tyyppi. Näin.

**Comment by amiika** [comment]
Show predicate @type (Ominaisuuden tyyppi) and range (Arvoalue) in predicateView.

Show datatype (Tietotyyppi) or valueClass (Viittauksen kohde) in propertyView based on predicate @type.

**Comment by lhahne** [comment]
displays datatype and valueclass if specified

**Comment by amiika** [comment]
If datatype or valueclass is not specified ... empty editable should added based on predicate @type:
owl:DatatypeProperty = datatype
owl:ObjectProperty = valueClass

**Comment by amiika** [comment]
Move dublicate type from predicateView to propertyView
